# Generated by Django 2.2.5 on 2020-09-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('iz_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('commission_type', models.CharField(choices=[('CIK', 1), ('OIK', 2), ('TIK', 3), ('UIK', 4), ('MIK', 5)], max_length=10)),
                ('address', models.CharField(max_length=2000)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('fax', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('end_date', models.CharField(blank=True, max_length=250, null=True)),
                ('address_voteroom', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_voteroom', models.CharField(blank=True, max_length=250, null=True)),
                ('lat_ik', models.CharField(blank=True, max_length=250, null=True)),
                ('lon_ik', models.CharField(blank=True, max_length=250, null=True)),
                ('lat_voteroom', models.CharField(blank=True, max_length=250, null=True)),
                ('lon_voteroom', models.CharField(blank=True, max_length=250, null=True)),
                ('snapshot_date', models.DateField()),
            ],
            options={
                'db_table': 'commission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('district_type', models.CharField(choices=[('REGION', 1), ('WHOLE_COUNTRY', 2), ('OKRUG', 3), ('RAYON', 4)], max_length=50)),
            ],
            options={
                'db_table': 'district',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nominator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('PARTY', 1), ('SELF_NOMINATION', 2), ('OTHER', 3)], max_length=50)),
                ('superior_nominator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ORM.Nominator')),
            ],
            options={
                'db_table': 'nominator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('election_level', models.CharField(choices=[('FEDERAL', 1), ('REGIONAL', 2), ('MUNICIPAL', 3)], max_length=50)),
                ('election_mandate_type', models.CharField(choices=[('SINGLE_MANDATE', 1), ('MULTI_MANDATE', 2), ('PARTY_LIST', 3)], max_length=50)),
                ('mandates', models.IntegerField()),
                ('election_date', models.DateField()),
                ('previous_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_elections', to='ORM.Election')),
                ('superior_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_elections', to='ORM.Election')),
            ],
            options={
                'db_table': 'election',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommissionProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_voters', models.IntegerField()),
                ('ballots_received', models.IntegerField()),
                ('ballots_given_out_early', models.IntegerField()),
                ('ballots_given_out_at_stations', models.IntegerField()),
                ('ballots_given_out_outside', models.IntegerField()),
                ('ballots_given_out_total', models.IntegerField()),
                ('canceled_ballots', models.IntegerField()),
                ('ballots_found_outside', models.IntegerField()),
                ('ballots_found_at_station', models.IntegerField()),
                ('ballots_found_total', models.IntegerField()),
                ('valid_ballots', models.IntegerField()),
                ('invalid_ballots', models.IntegerField()),
                ('lost_ballots', models.IntegerField()),
                ('appeared_ballots', models.IntegerField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.Commission')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.Election')),
            ],
            options={
                'db_table': 'commission_protocol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommissionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('position', models.CharField(choices=[('HEAD', 1), ('DEPUTY', 2), ('SECRETARY', 3), ('MEMBER', 4)], max_length=50)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.Commission')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.Nominator')),
            ],
            options={
                'db_table': 'commission_member',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ORM.Region'),
        ),
        migrations.AddField(
            model_name='commission',
            name='superior_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ORM.Commission'),
        ),
        migrations.CreateModel(
            name='CandidatePerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('candidate_type', models.CharField(choices=[('PARTY', 1), ('PERSON', 2), ('OTHER', 3)], max_length=20)),
                ('votes', models.IntegerField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.Commission')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.Election')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.Nominator')),
            ],
            options={
                'db_table': 'candidate_performance',
                'managed': True,
            },
        ),
    ]
