# Generated by Django 3.1 on 2020-08-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('party', 'party'), ('person', 'person'), ('other', 'other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('CIK', 'Centralnya'), ('OIK', 'Okruzhnaya'), ('TIK', 'Territorialnaya'), ('UIK', 'Uchastkovaya'), ('MIK', 'Municipalnaya')], max_length=10)),
                ('address', models.CharField(max_length=2000)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('fax', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('end_date', models.CharField(blank=True, max_length=250, null=True)),
                ('address_voteroom', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_voteroom', models.CharField(blank=True, max_length=250, null=True)),
                ('lat_ik', models.CharField(blank=True, max_length=250, null=True)),
                ('lon_ik', models.CharField(blank=True, max_length=250, null=True)),
                ('lat_voteroom', models.CharField(blank=True, max_length=250, null=True)),
                ('lon_voteroom', models.CharField(blank=True, max_length=250, null=True)),
                ('snapshot_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('region', 'region'), ('okrug', 'okrug'), ('rayon', 'rayon'), ('whole_country', 'whole_country')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nominator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('self_nomination', 'self_nomination'), ('other', 'other'), ('party', 'party')], max_length=50)),
                ('superior_nominator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ORM.nominator')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('level', models.CharField(choices=[('federal', 'federal'), ('regional', 'regional'), ('municipal', 'municipal')], max_length=50)),
                ('mandate_type', models.CharField(choices=[('single_mandate', 'single_mandate'), ('multi_mandate', 'multi_mandate'), ('party_list', 'party_list')], max_length=50)),
                ('mandates', models.IntegerField()),
                ('previous_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_elections', to='ORM.election')),
                ('superior_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_elections', to='ORM.election')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_voters', models.IntegerField()),
                ('ballots_received', models.IntegerField()),
                ('ballots_given_out_early', models.IntegerField()),
                ('ballots_given_out_at_stations', models.IntegerField()),
                ('ballots_given_out_outside', models.IntegerField()),
                ('canceled_ballots', models.IntegerField()),
                ('ballots_found_outside', models.IntegerField()),
                ('ballots_found_at_station', models.IntegerField()),
                ('valid_ballots', models.IntegerField()),
                ('invalid_ballots', models.IntegerField()),
                ('lost_ballots', models.IntegerField()),
                ('appeared_ballots', models.IntegerField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.commission')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.election')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('position', models.CharField(choices=[('head', 'head'), ('deputy', 'deputy'), ('secretary', 'secretary'), ('member', 'member')], max_length=50)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.commission')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.nominator')),
            ],
        ),
        migrations.AddField(
            model_name='commission',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ORM.region'),
        ),
        migrations.AddField(
            model_name='commission',
            name='superior_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ORM.commission'),
        ),
        migrations.CreateModel(
            name='CandidatePerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('votes', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.candidate')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.commission')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.election')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORM.nominator')),
            ],
        ),
    ]
